/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#2151da",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#2a1700",
        "surface-container-high": "#e2e7ff",
        "on-secondary-fixed": "#001e2f",
        "on-secondary-fixed-variant": "#004c6e",
        "on-surface": "#131b2e",
        "outline-variant": "#c4c5d7",
        "on-tertiary-container": "#ffcb8f",
        "error": "#ba1a1a",
        "on-primary-container": "#cad3ff",
        "secondary-fixed": "#c9e6ff",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-container": "#eaedff",
        "inverse-on-surface": "#eef0ff",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "on-background": "#131b2e",
        "on-primary-fixed-variant": "#0039b5",
        "secondary": "#006591",
        "outline": "#747686",
        "background": "#faf8ff",
        "secondary-container": "#39b8fd",
        "primary-fixed": "#dce1ff",
        "primary-container": "#1d4ed8",
        "secondary-fixed-dim": "#89ceff",
        "surface-container-low": "#f2f3ff",
        "on-primary": "#ffffff",
        "surface-variant": "#dae2fd",
        "inverse-surface": "#283044",
        "on-tertiary-fixed-variant": "#653e00",
        "surface": "#faf8ff",
        "tertiary-fixed": "#ffddb8",
        "surface-container-highest": "#dae2fd",
        "tertiary-container": "#825100",
        "on-error-container": "#93000a",
        "surface-dim": "#d2d9f4",
        "on-secondary-container": "#004666",
        "primary-fixed-dim": "#b7c4ff",
        "on-surface-variant": "#434655",
        "surface-bright": "#faf8ff",
        "inverse-primary": "#b7c4ff",
        "on-primary-fixed": "#001551",
        "primary": "#0037b0",
        "tertiary": "#623c00",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff"
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-hero': ['48px', { lineHeight: '56px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'display-hero-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0em', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        '2xs': '0.25rem',
        'xs': '0.5rem',
        'sm': '0.75rem',
        'md': '1rem',
        'lg': '1.5rem',
        'xl': '2rem',
        '2xl': '3rem',
        '3xl': '4rem',
        'margin-desktop': '2.5rem',
        'margin-tablet': '1.5rem',
        'margin-mobile': '1rem',
      },
    },
  },
  plugins: [],
}
